[workspace.package]
license = "MIT-0"
authors = ["QX Ventures <info@qx.ventures>"]
homepage = "https://qx.ventures/"
repository = "https://github.com/qx-ventures/qxchain.git"
edition = "2021"

[workspace]
default-members = ["node", "runtime"]
members = [
    "node",
    "pallets/pallet-qx-ai",
    "runtime",
]
resolver = "2"

[workspace.dependencies]
qxchain-runtime = { path = "./runtime", default-features = false }
clap = { version = "4.5.13" }
docify = { version = "0.2.9" }
futures = { version = "0.3.31" }
futures-timer = { version = "3.0.2" }
jsonrpsee = { version = "0.24.3" }
polkadot-sdk = { version = "2503.0.1", default-features = false }
codec = { version = "3.7.4", default-features = false, package = "parity-scale-codec" }
scale-info = { version = "2.11.6", default-features = false }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.132", default-features = false }

[profile.release]
opt-level = 3
panic = "unwind"

[profile.production]
codegen-units = 4        # Balance between optimization and memory (was 1) TODO: Use 1 for production
inherits = "release"
lto = "thin"             # Use thin LTO instead of full (less memory) TODO: Use full for production

