[package]
name = "qxchain-runtime"
description = "QXChain runtime built with Substrate for ML inference on blockchain."
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[dependencies]
codec = { workspace = true }
pallet-ml-inference = { path = "../pallets/pallet-ml-inference", default-features = false }
pallet-ml-models = { path = "../pallets/pallet-ml-models", default-features = false }
polkadot-sdk = { workspace = true, features = ["pallet-balances", "pallet-sudo", "pallet-timestamp", "pallet-transaction-payment", "pallet-transaction-payment-rpc-runtime-api", "runtime"] }
scale-info = { workspace = true }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }

[build-dependencies]
polkadot-sdk = { optional = true, workspace = true, features = ["substrate-wasm-builder"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-ml-inference/std",
	"pallet-ml-models/std",
	"polkadot-sdk/std",
	"scale-info/std",
	"serde_json/std",
]
