[package]
name = "qxchain-runtime"
description = "QX Chain runtime for decentralized AI inference validation with opML consensus."
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[dependencies]
codec = { workspace = true }
pallet-qx-ai = { path = "../pallets/pallet-qx-ai", default-features = false }
pallet-qx-kilt-permissions = { path = "../pallets/pallet-qx-kilt-permissions", default-features = false }
polkadot-sdk = { workspace = true, features = [
	"frame-executive",
	"frame-metadata-hash-extension",
	"frame-support",
	"frame-system",
	"frame-system-benchmarking",
	"frame-system-rpc-runtime-api",
	"frame-try-runtime",
	"frame-benchmarking",
	"pallet-aura",
	"pallet-balances",
	"pallet-grandpa",
	"pallet-sudo",
	"pallet-timestamp",
	"pallet-transaction-payment",
	"pallet-transaction-payment-rpc-runtime-api",
	"sp-api",
	"sp-block-builder",
	"sp-consensus-aura",
	"sp-consensus-grandpa",
	"sp-core",
	"sp-genesis-builder",
	"sp-inherents",
	"sp-keyring",
	"sp-offchain",
	"sp-runtime",
	"sp-session",
	"sp-storage",
	"sp-transaction-pool",
	"sp-version",
	"runtime"
] }
scale-info = { workspace = true }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }

[build-dependencies]
substrate-wasm-builder = { version = "25.0.0", optional = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-qx-ai/std",
	"pallet-qx-kilt-permissions/std",
	"polkadot-sdk/std",
	"scale-info/std",
	"serde_json/std",
	"substrate-wasm-builder",
]
