#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(feature = "std")]
include!(concat!(env!("OUT_DIR"), "/wasm_binary.rs"));

extern crate alloc;
use alloc::vec::Vec;

// Import everything from polkadot_sdk
use polkadot_sdk::*;
use polkadot_sdk::sp_runtime::{
	generic, impl_opaque_keys,
	traits::{BlakeTwo256, IdentifyAccount, Verify},
	MultiAddress, MultiSignature,
};
#[cfg(feature = "std")]
use polkadot_sdk::sp_version::NativeVersion;
use polkadot_sdk::sp_version::RuntimeVersion;

use polkadot_sdk::frame_support::{
	derive_impl, parameter_types,
	genesis_builder_helper::{build_state, get_preset},
	traits::{ConstBool, ConstU128, ConstU32, ConstU64, ConstU8, VariantCountOf},
	pallet_prelude::One,
	weights::{
		constants::{RocksDbWeight, WEIGHT_REF_TIME_PER_SECOND},
		IdentityFee, Weight,
	},
};
use polkadot_sdk::frame_system::limits::{BlockLength, BlockWeights};
use polkadot_sdk::pallet_transaction_payment::{ConstFeeMultiplier, FungibleAdapter, Multiplier};
use polkadot_sdk::sp_consensus_aura::sr25519::AuthorityId as AuraId;
use polkadot_sdk::sp_consensus_grandpa::AuthorityId as GrandpaId;
use polkadot_sdk::sp_keyring::{Ed25519Keyring, Sr25519Keyring};

pub use polkadot_sdk::frame_system::Call as SystemCall;
pub use polkadot_sdk::pallet_balances::Call as BalancesCall;
pub use polkadot_sdk::pallet_timestamp::Call as TimestampCall;
#[cfg(any(feature = "std", test))]
pub use polkadot_sdk::sp_runtime::BuildStorage;

/// Opaque types. These are used by the CLI to instantiate machinery that don't need to know
/// the specifics of the runtime. They can then be made to be agnostic over specific formats
/// of data like extrinsics, allowing for them to continue syncing the network through upgrades
/// to even the core data structures.
pub mod opaque {
	use super::*;
	use polkadot_sdk::sp_runtime::{
		generic,
		traits::{BlakeTwo256, Hash as HashT},
	};

	pub use polkadot_sdk::sp_runtime::OpaqueExtrinsic as UncheckedExtrinsic;

	/// Opaque block header type.
	pub type Header = generic::Header<BlockNumber, BlakeTwo256>;
	/// Opaque block type.
	pub type Block = generic::Block<Header, UncheckedExtrinsic>;
	/// Opaque block identifier type.
	pub type BlockId = generic::BlockId<Block>;
	/// Opaque block hash type.
	pub type Hash = <BlakeTwo256 as HashT>::Output;
}

impl_opaque_keys! {
	pub struct SessionKeys {
		pub aura: Aura,
		pub grandpa: Grandpa,
	}
}

// To learn more about runtime versioning, see:
// https://docs.substrate.io/main-docs/build/upgrade#runtime-versioning
#[polkadot_sdk::sp_version::runtime_version]
pub const VERSION: RuntimeVersion = RuntimeVersion {
	spec_name: alloc::borrow::Cow::Borrowed("qxchain"),
	impl_name: alloc::borrow::Cow::Borrowed("qxchain"),
	authoring_version: 1,
	// The version of the runtime specification. A full node will not attempt to use its native
	//   runtime in substitute for the on-chain Wasm runtime unless all of `spec_name`,
	//   `spec_version`, and `authoring_version` are the same between Wasm and native.
	// This value is set to 100 to notify Polkadot-JS App (https://polkadot.js.org/apps) to use
	//   the compatible custom types.
	spec_version: 100,
	impl_version: 1,
	apis: RUNTIME_API_VERSIONS,  // This will be generated by impl_runtime_apis! macro
	transaction_version: 1,
	system_version: 1,
};

/// This determines the average expected block time that we are targeting.
/// Blocks will be produced at a minimum duration defined by `SLOT_DURATION`.
/// `SLOT_DURATION` is picked up by `pallet_timestamp` which is in turn picked up
/// by `pallet_aura` to implement `fn slot_duration()`.
///
/// Change this to adjust the block time.
pub const MILLI_SECS_PER_BLOCK: u64 = 6000;

// NOTE: Currently it is not possible to change the slot duration after the chain has started.
//       Attempting to do so will brick block production.
pub const SLOT_DURATION: u64 = MILLI_SECS_PER_BLOCK;

// Time is measured by number of blocks.
pub const MINUTES: BlockNumber = 60_000 / (MILLI_SECS_PER_BLOCK as BlockNumber);
pub const HOURS: BlockNumber = MINUTES * 60;
pub const DAYS: BlockNumber = HOURS * 24;

/// The version information used to identify this runtime when compiled natively.
#[cfg(feature = "std")]
pub fn native_version() -> NativeVersion {
	NativeVersion { runtime_version: VERSION, can_author_with: Default::default() }
}

// Configure FRAME pallets to include in runtime.

/// An index to a block.
pub type BlockNumber = u32;

/// Alias to 512-bit hash when used in the context of a transaction signature on the chain.
pub type Signature = MultiSignature;

/// Some way of identifying an account on the chain. We intentionally make it equivalent
/// to the public key of our transaction signing scheme.
pub type AccountId = <<Signature as Verify>::Signer as IdentifyAccount>::AccountId;

/// Balance of an account.
pub type Balance = u128;

/// Index of a transaction in the chain.
pub type Nonce = u32;

/// A hash of some data used by the chain.
pub type Hash = polkadot_sdk::sp_core::H256;

/// The address format for describing accounts.
pub type Address = MultiAddress<AccountId, ()>;

/// Block header type as expected by this runtime.
pub type Header = generic::Header<BlockNumber, BlakeTwo256>;

/// Block type as expected by this runtime.
pub type Block = generic::Block<Header, UncheckedExtrinsic>;

/// A Block signed with a Justification
pub type SignedBlock = generic::SignedBlock<Block>;

/// BlockId type as expected by this runtime.
pub type BlockId = generic::BlockId<Block>;

/// The SignedExtension to the basic transaction logic.
pub type SignedExtra = (
	frame_system::CheckNonZeroSender<Runtime>,
	frame_system::CheckSpecVersion<Runtime>,
	frame_system::CheckTxVersion<Runtime>,
	frame_system::CheckGenesis<Runtime>,
	frame_system::CheckEra<Runtime>,
	frame_system::CheckNonce<Runtime>,
	frame_system::CheckWeight<Runtime>,
	pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
	frame_metadata_hash_extension::CheckMetadataHash<Runtime>,
);

/// Unchecked extrinsic type as expected by this runtime.
pub type UncheckedExtrinsic =
	generic::UncheckedExtrinsic<Address, RuntimeCall, Signature, SignedExtra>;

/// The payload being signed in transactions.
pub type SignedPayload = generic::SignedPayload<RuntimeCall, SignedExtra>;

/// Executive: handles dispatch to the various modules.
pub type Executive = frame_executive::Executive<
	Runtime,
	Block,
	frame_system::ChainContext<Runtime>,
	Runtime,
	AllPalletsWithSystem,
>;

/// The minimum amount required to keep an account open. MUST BE GREATER THAN ZERO!
pub const EXISTENTIAL_DEPOSIT: Balance = 500;

const NORMAL_DISPATCH_RATIO: polkadot_sdk::sp_runtime::Perbill = polkadot_sdk::sp_runtime::Perbill::from_percent(75);

parameter_types! {
	pub const BlockHashCount: BlockNumber = 2400;
	pub const Version: RuntimeVersion = VERSION;
	pub RuntimeBlockWeights: BlockWeights = BlockWeights::with_sensible_defaults(
		Weight::from_parts(2u64 * WEIGHT_REF_TIME_PER_SECOND, u64::MAX),
		NORMAL_DISPATCH_RATIO,
	);
	pub RuntimeBlockLength: BlockLength = BlockLength::max_with_normal_ratio(5 * 1024 * 1024, NORMAL_DISPATCH_RATIO);
	pub const SS58Prefix: u8 = 42;
}

/// The default types are being injected by [`derive_impl`](`frame_support::derive_impl`) from
/// [`SoloChainDefaultConfig`](`struct@frame_system::config_preludes::SolochainDefaultConfig`),
/// but overridden as needed.
#[derive_impl(frame_system::config_preludes::SolochainDefaultConfig)]
impl frame_system::Config for Runtime {
	/// The block type for the runtime.
	type Block = Block;
	/// Block & extrinsics weights: base values and limits.
	type BlockWeights = RuntimeBlockWeights;
	/// The maximum length of a block (in bytes).
	type BlockLength = RuntimeBlockLength;
	/// The identifier used to distinguish between accounts.
	type AccountId = AccountId;
	/// The type for storing how many extrinsics an account has signed.
	type Nonce = Nonce;
	/// The type for hashing blocks and tries.
	type Hash = Hash;
	/// Maximum number of block number to block hash mappings to keep (oldest pruned first).
	type BlockHashCount = BlockHashCount;
	/// The weight of database operations that the runtime can invoke.
	type DbWeight = RocksDbWeight;
	/// Version of the runtime.
	type Version = Version;
	/// The data to be stored in an account.
	type AccountData = pallet_balances::AccountData<Balance>;
	/// This is used as an identifier of the chain. 42 is the generic substrate prefix.
	type SS58Prefix = SS58Prefix;
	type MaxConsumers = frame_support::traits::ConstU32<16>;
}

impl pallet_aura::Config for Runtime {
	type AuthorityId = AuraId;
	type DisabledValidators = ();
	type MaxAuthorities = ConstU32<32>;
	type AllowMultipleBlocksPerSlot = ConstBool<false>;
	type SlotDuration = pallet_aura::MinimumPeriodTimesTwo<Runtime>;
}

impl pallet_grandpa::Config for Runtime {
	type RuntimeEvent = RuntimeEvent;
	type WeightInfo = ();
	type MaxAuthorities = ConstU32<32>;
	type MaxNominators = ConstU32<0>;
	type MaxSetIdSessionEntries = ConstU64<0>;
	type KeyOwnerProof = polkadot_sdk::sp_core::Void;
	type EquivocationReportSystem = ();
}

impl pallet_timestamp::Config for Runtime {
	/// A timestamp: milliseconds since the unix epoch.
	type Moment = u64;
	type OnTimestampSet = Aura;
	type MinimumPeriod = ConstU64<{ SLOT_DURATION / 2 }>;
	type WeightInfo = ();
}

impl pallet_balances::Config for Runtime {
	type MaxLocks = ConstU32<50>;
	type MaxReserves = ();
	type ReserveIdentifier = [u8; 8];
	/// The type for recording an account's balance.
	type Balance = Balance;
	/// The ubiquitous event type.
	type RuntimeEvent = RuntimeEvent;
	type DustRemoval = ();
	type ExistentialDeposit = ConstU128<EXISTENTIAL_DEPOSIT>;
	type AccountStore = System;
	type WeightInfo = pallet_balances::weights::SubstrateWeight<Runtime>;
	type FreezeIdentifier = RuntimeFreezeReason;
	type MaxFreezes = VariantCountOf<RuntimeFreezeReason>;
	type RuntimeHoldReason = RuntimeHoldReason;
	type RuntimeFreezeReason = RuntimeFreezeReason;
	type DoneSlashHandler = ();
}

parameter_types! {
	pub FeeMultiplier: Multiplier = Multiplier::one();
}

impl pallet_transaction_payment::Config for Runtime {
	type RuntimeEvent = RuntimeEvent;
	type OnChargeTransaction = FungibleAdapter<Balances, ()>;
	type OperationalFeeMultiplier = ConstU8<5>;
	type WeightToFee = IdentityFee<Balance>;
	type LengthToFee = IdentityFee<Balance>;
	type FeeMultiplierUpdate = ConstFeeMultiplier<FeeMultiplier>;
	type WeightInfo = pallet_transaction_payment::weights::SubstrateWeight<Runtime>;
}

impl pallet_sudo::Config for Runtime {
	type RuntimeEvent = RuntimeEvent;
	type RuntimeCall = RuntimeCall;
	type WeightInfo = pallet_sudo::weights::SubstrateWeight<Runtime>;
}

/// Configure the QX AI pallet
impl pallet_qx_ai::Config for Runtime {
	type RuntimeEvent = RuntimeEvent;
	type Currency = Balances;
	type MinAIWorkerStake = ConstU128<{ 1_000 * EXISTENTIAL_DEPOSIT }>;
	type MinChallengeStake = ConstU128<{ 100 * EXISTENTIAL_DEPOSIT }>;
	type ChallengePeriod = ConstU32<{ 7 * DAYS }>;  // 7 days challenge period
	type SlashThreshold = ConstU32<51>;  // 51% threshold for slashing
	type MaxQueueSize = ConstU32<100>;  // Max 100 requests per worker
}

// Create the runtime by composing the FRAME pallets that were previously configured.
#[frame_support::runtime]
mod runtime {
	#[runtime::runtime]
	#[runtime::derive(
		RuntimeCall,
		RuntimeEvent,
		RuntimeError,
		RuntimeOrigin,
		RuntimeFreezeReason,
		RuntimeHoldReason,
		RuntimeSlashReason,
		RuntimeLockId,
		RuntimeTask,
		RuntimeViewFunction
	)]
	pub struct Runtime;

	#[runtime::pallet_index(0)]
	pub type System = polkadot_sdk::frame_system;

	#[runtime::pallet_index(1)]
	pub type Timestamp = polkadot_sdk::pallet_timestamp;

	#[runtime::pallet_index(2)]
	pub type Aura = polkadot_sdk::pallet_aura;

	#[runtime::pallet_index(3)]
	pub type Grandpa = polkadot_sdk::pallet_grandpa;

	#[runtime::pallet_index(4)]
	pub type Balances = polkadot_sdk::pallet_balances;

	#[runtime::pallet_index(5)]
	pub type TransactionPayment = polkadot_sdk::pallet_transaction_payment;

	#[runtime::pallet_index(6)]
	pub type Sudo = polkadot_sdk::pallet_sudo;

	#[runtime::pallet_index(7)]
	pub type QxAi = pallet_qx_ai;
}

/// All migrations that will run on the next runtime upgrade.
///
/// This contains the combined migrations of all pallets.
pub type Migrations = ();

// Runtime APIs implementation using impl_runtime_apis! macro
polkadot_sdk::sp_api::impl_runtime_apis! {
	impl polkadot_sdk::sp_api::Core<Block> for Runtime {
		fn version() -> RuntimeVersion {
			VERSION
		}

		fn execute_block(block: Block) {
			Executive::execute_block(block);
		}

		fn initialize_block(header: &<Block as polkadot_sdk::sp_runtime::traits::Block>::Header) -> polkadot_sdk::sp_runtime::ExtrinsicInclusionMode {
			Executive::initialize_block(header)
		}
	}

	impl polkadot_sdk::sp_api::Metadata<Block> for Runtime {
		fn metadata() -> polkadot_sdk::sp_core::OpaqueMetadata {
			polkadot_sdk::sp_core::OpaqueMetadata::new(Runtime::metadata().into())
		}

		fn metadata_at_version(version: u32) -> Option<polkadot_sdk::sp_core::OpaqueMetadata> {
			Runtime::metadata_at_version(version)
		}

		fn metadata_versions() -> alloc::vec::Vec<u32> {
			Runtime::metadata_versions()
		}
	}

	impl polkadot_sdk::sp_block_builder::BlockBuilder<Block> for Runtime {
		fn apply_extrinsic(extrinsic: <Block as polkadot_sdk::sp_runtime::traits::Block>::Extrinsic) -> polkadot_sdk::sp_runtime::ApplyExtrinsicResult {
			Executive::apply_extrinsic(extrinsic)
		}

		fn finalize_block() -> <Block as polkadot_sdk::sp_runtime::traits::Block>::Header {
			Executive::finalize_block()
		}

		fn inherent_extrinsics(data: polkadot_sdk::sp_inherents::InherentData) -> Vec<<Block as polkadot_sdk::sp_runtime::traits::Block>::Extrinsic> {
			data.create_extrinsics()
		}

		fn check_inherents(
			block: Block,
			data: polkadot_sdk::sp_inherents::InherentData,
		) -> polkadot_sdk::sp_inherents::CheckInherentsResult {
			data.check_extrinsics(&block)
		}
	}

	impl polkadot_sdk::sp_transaction_pool::runtime_api::TaggedTransactionQueue<Block> for Runtime {
		fn validate_transaction(
			source: polkadot_sdk::sp_runtime::transaction_validity::TransactionSource,
			tx: <Block as polkadot_sdk::sp_runtime::traits::Block>::Extrinsic,
			block_hash: <Block as polkadot_sdk::sp_runtime::traits::Block>::Hash,
		) -> polkadot_sdk::sp_runtime::transaction_validity::TransactionValidity {
			Executive::validate_transaction(source, tx, block_hash)
		}
	}

	impl polkadot_sdk::sp_offchain::OffchainWorkerApi<Block> for Runtime {
		fn offchain_worker(header: &<Block as polkadot_sdk::sp_runtime::traits::Block>::Header) {
			Executive::offchain_worker(header)
		}
	}

	impl polkadot_sdk::sp_consensus_aura::AuraApi<Block, AuraId> for Runtime {
		fn slot_duration() -> polkadot_sdk::sp_consensus_aura::SlotDuration {
			polkadot_sdk::sp_consensus_aura::SlotDuration::from_millis(Aura::slot_duration())
		}

		fn authorities() -> Vec<AuraId> {
			polkadot_sdk::pallet_aura::Authorities::<Runtime>::get().into_inner()
		}
	}

	impl polkadot_sdk::sp_session::SessionKeys<Block> for Runtime {
		fn generate_session_keys(seed: Option<Vec<u8>>) -> Vec<u8> {
			SessionKeys::generate(seed)
		}

		fn decode_session_keys(
			encoded: Vec<u8>,
		) -> Option<Vec<(Vec<u8>, polkadot_sdk::sp_core::crypto::KeyTypeId)>> {
			SessionKeys::decode_into_raw_public_keys(&encoded)
		}
	}

	impl polkadot_sdk::sp_consensus_grandpa::GrandpaApi<Block> for Runtime {
		fn grandpa_authorities() -> polkadot_sdk::sp_consensus_grandpa::AuthorityList {
			Grandpa::grandpa_authorities()
		}

		fn current_set_id() -> polkadot_sdk::sp_consensus_grandpa::SetId {
			Grandpa::current_set_id()
		}

		fn submit_report_equivocation_unsigned_extrinsic(
			_equivocation_proof: polkadot_sdk::sp_consensus_grandpa::EquivocationProof<
				<Block as polkadot_sdk::sp_runtime::traits::Block>::Hash,
				polkadot_sdk::sp_runtime::traits::NumberFor<Block>,
			>,
			_key_owner_proof: polkadot_sdk::sp_consensus_grandpa::OpaqueKeyOwnershipProof,
		) -> Option<()> {
			None
		}

		fn generate_key_ownership_proof(
			_set_id: polkadot_sdk::sp_consensus_grandpa::SetId,
			_authority_id: polkadot_sdk::sp_consensus_grandpa::AuthorityId,
		) -> Option<polkadot_sdk::sp_consensus_grandpa::OpaqueKeyOwnershipProof> {
			// NOTE: this is the only implementation possible since we've
			// defined our key owner proof type as a bottom type (i.e. a type
			// with no values).
			None
		}
	}

	impl polkadot_sdk::frame_system_rpc_runtime_api::AccountNonceApi<Block, AccountId, Nonce> for Runtime {
		fn account_nonce(account: AccountId) -> Nonce {
			System::account_nonce(account)
		}
	}

	impl polkadot_sdk::pallet_transaction_payment_rpc_runtime_api::TransactionPaymentApi<Block, Balance> for Runtime {
		fn query_info(
			uxt: <Block as polkadot_sdk::sp_runtime::traits::Block>::Extrinsic,
			len: u32,
		) -> polkadot_sdk::pallet_transaction_payment_rpc_runtime_api::RuntimeDispatchInfo<Balance> {
			TransactionPayment::query_info(uxt, len)
		}
		fn query_fee_details(
			uxt: <Block as polkadot_sdk::sp_runtime::traits::Block>::Extrinsic,
			len: u32,
		) -> polkadot_sdk::pallet_transaction_payment::FeeDetails<Balance> {
			TransactionPayment::query_fee_details(uxt, len)
		}
		fn query_weight_to_fee(weight: Weight) -> Balance {
			TransactionPayment::weight_to_fee(weight)
		}
		fn query_length_to_fee(length: u32) -> Balance {
			TransactionPayment::length_to_fee(length)
		}
	}

	impl polkadot_sdk::pallet_transaction_payment_rpc_runtime_api::TransactionPaymentCallApi<Block, Balance, RuntimeCall>
		for Runtime
	{
		fn query_call_info(
			call: RuntimeCall,
			len: u32,
		) -> polkadot_sdk::pallet_transaction_payment::RuntimeDispatchInfo<Balance> {
			TransactionPayment::query_call_info(call, len)
		}
		fn query_call_fee_details(
			call: RuntimeCall,
			len: u32,
		) -> polkadot_sdk::pallet_transaction_payment::FeeDetails<Balance> {
			TransactionPayment::query_call_fee_details(call, len)
		}
		fn query_weight_to_fee(weight: Weight) -> Balance {
			TransactionPayment::weight_to_fee(weight)
		}
		fn query_length_to_fee(length: u32) -> Balance {
			TransactionPayment::length_to_fee(length)
		}
	}

	#[cfg(feature = "runtime-benchmarks")]
	impl polkadot_sdk::frame_benchmarking::Benchmark<Block> for Runtime {
		fn benchmark_metadata(extra: bool) -> (
			Vec<polkadot_sdk::frame_benchmarking::BenchmarkList>,
			Vec<polkadot_sdk::frame_support::traits::StorageInfo>,
		) {
			use polkadot_sdk::frame_benchmarking::{baseline, Benchmarking, BenchmarkList};
			use polkadot_sdk::frame_support::traits::StorageInfoTrait;
			use polkadot_sdk::frame_system_benchmarking::Pallet as SystemBench;
			use polkadot_sdk::frame_benchmarking::baseline::Pallet as BaselineBench;

			let mut list = Vec::<BenchmarkList>::new();
			list_benchmarks!(list, extra);

			let storage_info = AllPalletsWithSystem::storage_info();

			(list, storage_info)
		}

		fn dispatch_benchmark(
			config: polkadot_sdk::frame_benchmarking::BenchmarkConfig
		) -> Result<Vec<polkadot_sdk::frame_benchmarking::BenchmarkBatch>, alloc::string::String> {
			use polkadot_sdk::frame_benchmarking::{baseline, Benchmarking, BenchmarkBatch};
			use polkadot_sdk::sp_storage::TrackedStorageKey;
			use polkadot_sdk::frame_system_benchmarking::Pallet as SystemBench;
			use polkadot_sdk::frame_benchmarking::baseline::Pallet as BaselineBench;

			impl polkadot_sdk::frame_system_benchmarking::Config for Runtime {}
			impl polkadot_sdk::frame_benchmarking::baseline::Config for Runtime {}

			use polkadot_sdk::frame_support::traits::WhitelistedStorageKeys;
			let whitelist: Vec<TrackedStorageKey> = AllPalletsWithSystem::whitelisted_storage_keys();

			let mut batches = Vec::<BenchmarkBatch>::new();
			let params = (&config, &whitelist);
			add_benchmarks!(params, batches);

			Ok(batches)
		}
	}

	#[cfg(feature = "try-runtime")]
	impl polkadot_sdk::frame_try_runtime::TryRuntime<Block> for Runtime {
		fn on_runtime_upgrade(checks: polkadot_sdk::frame_try_runtime::UpgradeCheckSelect) -> (Weight, Weight) {
			let weight = Executive::try_runtime_upgrade(checks).unwrap();
			(weight, RuntimeBlockWeights::get().max_block)
		}

		fn execute_block(
			block: Block,
			state_root_check: bool,
			signature_check: bool,
			select: polkadot_sdk::frame_try_runtime::TryStateSelect,
		) -> Weight {
			Executive::try_execute_block(block, state_root_check, signature_check, select).unwrap()
		}
	}

	impl polkadot_sdk::sp_genesis_builder::GenesisBuilder<Block> for Runtime {
		fn build_state(config: Vec<u8>) -> polkadot_sdk::sp_genesis_builder::Result {
			build_state::<RuntimeGenesisConfig>(config)
		}

		fn get_preset(id: &Option<polkadot_sdk::sp_genesis_builder::PresetId>) -> Option<Vec<u8>> {
			get_preset::<RuntimeGenesisConfig>(id, genesis_config_presets::get_preset)
		}

		fn preset_names() -> Vec<polkadot_sdk::sp_genesis_builder::PresetId> {
			genesis_config_presets::preset_names()
		}
	}
}

// Provides getters for genesis configuration presets.
pub mod genesis_config_presets {
	use super::*;
	use alloc::vec;

	/// Returns a development genesis config preset.
	pub fn get_preset(id: &polkadot_sdk::sp_genesis_builder::PresetId) -> Option<Vec<u8>> {
		let patch = match id.as_ref() {
			polkadot_sdk::sp_genesis_builder::DEV_RUNTIME_PRESET => {
				let endowment = Balance::MAX / 1000;
				// Create initial authorities with both Aura (Sr25519) and Grandpa (Ed25519) keys
				let initial_authorities: Vec<(AuraId, GrandpaId)> = vec![
					(
						Sr25519Keyring::Alice.public().into(),
						Ed25519Keyring::Alice.public().into(),
					),
				];

				serde_json::json!({
					"balances": {
						"balances": Sr25519Keyring::iter()
							.map(|a| (a.to_account_id(), endowment))
							.collect::<Vec<_>>(),
					},
					"sudo": {
						"key": Sr25519Keyring::Alice.to_account_id()
					},
					"aura": {
						"authorities": initial_authorities.iter().map(|x| x.0.clone()).collect::<Vec<_>>(),
					},
					"grandpa": {
						"authorities": initial_authorities.iter().map(|x| (x.1.clone(), 1)).collect::<Vec<_>>(),
					},
				})
			}
			_ => return None,
		};

		Some(
			serde_json::to_string(&patch)
				.expect("serialization to json is expected to work. qed.")
				.into_bytes(),
		)
	}

	/// Get the list of available preset names
	pub fn preset_names() -> Vec<polkadot_sdk::sp_genesis_builder::PresetId> {
		vec![polkadot_sdk::sp_genesis_builder::DEV_RUNTIME_PRESET.into()]
	}
}

