[package]
name = "qxchain"
description = "A minimal Substrate-based Substrate node, ready for hacking."
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
build = "build.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[[bin]]
name = "qxchain"
path = "src/main.rs"

[lib]
name = "qxchain_node"
path = "src/lib.rs"

[dependencies]
clap = { features = ["derive"], workspace = true }
docify = { workspace = true }
futures = { features = ["thread-pool"], workspace = true }
futures-timer = { workspace = true }
jsonrpsee = { features = ["server"], workspace = true }
qxchain-runtime.workspace = true
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
polkadot-sdk = { workspace = true, features = [
	"experimental",
	"node",
	"sc-chain-spec",
	"sc-consensus-aura",
	"sc-consensus-grandpa",
	"sp-consensus-aura",
	"sp-consensus-grandpa"
] }

[build-dependencies]
polkadot-sdk = { workspace = true, features = ["substrate-build-script-utils"] }

[features]
default = ["std"]
std = [
	"qxchain-runtime/std",
	"polkadot-sdk/std",
]
